Fix offset for iOS 13
SniperGER/ProudLock2 pull request #14
Opened 2020-06-18 15:56 UTC by ryannair05

2020-06-20 20:54 UTC, SniperGER requested changes
Confirmed to be working on iOS 12 (iPhone 5s) and iOS 13 (iPad Pro 10.5"). However, it doesn't seem to make any difference.

Please note that moving the offset "calculation" to `- [SBFLockScreenDateView initWithFrame:]` requires every code path to have a return value, which isn't given by your check for `JPWeatherManager`. Probably a Copy & Paste error?

2020-06-20 20:54 UTC, SniperGER commented on Tweak.xm
> +    }
**Required:** This part needs to ```return %orig```.

2020-06-20 20:54 UTC, SniperGER commented on Tweak.xm
> +-(id)initWithFrame:(CGRect)arg1 {
_Note:_ Keep the formatting in line with the rest of the code. Not necessary, but it looks nicer.
```- (id)initWithFrame:(CGRect)arg1 {``` (note the space between ```-``` and ```(id)``)

2020-06-20 20:54 UTC, SniperGER commented on Tweak.xm
> +%end	// %hook CSCombinedListViewController
_Note:_ ```%hook```s inside ```%group```s are generally commented with three slashes in my code, as it keeps things a little more structured in my opinion. Again, this isn't necessary whatsoever, but I think it's nicer to keep a consistent code style.

2020-06-22 20:58 UTC, ryannair05 commented
Yeah, sorry about that copy and paste area. If you try to play media or get a notification these changes fix them from overlapping other components of the lockscreen. I also changed the MSHookFunction to only run on iOS 12 as from my testing it is not needed on iOS 13

2020-06-23 07:07 UTC, SniperGER commented
Thanks for the update! I'll have a look at it later today.

2020-06-23 21:33 UTC, SniperGER commented
Everything seems to be working on my testing devices so far, so I'm going to merge this. Now we just need a solution to the padlock overlapping the passcode UI on smaller devices, such as the iPhone 5s. Maybe there's a way to visually hide it when it transitions to the passcode buttons (as an optional setting, of course).

2020-06-23 21:33 UTC, merged